version: '3.8'

services:
  app-monitor:
    image: app-monitor-frontend:latest
    container_name: app_monitor_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production